#!/bin/sh
#!/bin/bash

PORT=64000
SERV="localhost"

if CONT=$(zenity --entry --title="Time Zone Apps" --text="Continent location:")
then if CITY=$(zenity --entry --title="Time Zone Apps" --text="City location:" )
then echo "ok"
else echo "no text input"
fi
else echo "no text input"
fi

ZONE="$CONT/$CITY"
OUT=$(echo ZONE | nc $SERV $PORT)


zenity --info \
--text="$(cat $OUT)"

rm PORT
rm SERV
