#!/bin/sh
#!/bin/bash


PORT=1234
SERV="localhost"

if CONT=$(zenity --entry --title `gettext -d tz-client "Time Zone Apps"` --text `gettext -d tz-client "Continent location:"`)
then if CITY=$(zenity --entry --title `gettext -d tz-client "Time Zone Apps"` --text `gettext -d tz-client "City location:"` )
then echo `gettext -d tz-client "ok"`
else echo `gettext -d tz-client "no text input"`
fi
else echo `gettext -d tz-client "no text input"`
fi

ZONE="$CONT/$CITY"
OUT=$(echo $ZONE | nc $SERV $PORT)


zenity --info \
--text="$(echo $OUT)"

