#!/bin/sh

TAMPON=/tmp/tz-$$
printf "Your continent : "
read CONTINENT
printf "Your city : "
read CITY
printf "Time Zone found : "
TZ=$CONTINENT/$CITY 'date' > $TAMPON
RESULT=$(cat $TAMPON)
echo $RESULT